from BigMartSales.components.data_ingestion import DataIngestion
from BigMartSales.components.data_validation import DataValidation
from BigMartSales.components.data_transformation import DataTransformation
from BigMartSales.components.model_trainer import ModelTrainer
from BigMartSales.components.model_evaluation import ModelEvaluation
from BigMartSales.components.model_pusher import ModelPusher